apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podcast-api-synethetic
  description: Podcast API
  tags:
    - java
  annotations:
    dynatrace.com/synthetics-ids: SYNTHETIC_TEST-2848D0525FB408EB
    
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: podcast
