apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher-service
  description: Searcher
  tags:
    - go
  annotations:
    dynatrace.com/dynatrace-entity-id: SERVICE-759A6D8A39A03733, SERVICE-FC7CA15F83519D1C, SERVICE-FC1DF2270D37D6AB

spec:
  type: service
  lifecycle: production
  owner: user:guest
